goods/urls.py
from django.conf.urls import url
from django.views.decorators.cache import never_cache
from goods.views import GoodsPageView, GoodDetailPageView, GoodCreateView, GoodUpdateView, CategoryListView, category_menu
from tinymce.views import spell_check, filebrowser, css, spell_check_callback

urlpatterns = [
    url(r'^(?:(?P<pk>\d+)/)?$', never_cache(GoodsPageView.as_view()), name="goods"),
    url(r'^(?P<pk>\d+)/detail/$', never_cache(GoodDetailPageView.as_view()), name="goods_detail"),
    url(r'^(?P<pk>\d+)/add/$', GoodCreateView.as_view(), name="goods_add"),
    url(r'^(?P<pk>\d+)/edit/$', GoodUpdateView.as_view(), name="goods_edit"),
    url(r'category_list', CategoryListView.as_view(), name="category_list"),
    url(r'category_menu', category_menu, name="category_menu"),
    url(r'^spellchecker/$', spell_check, name='tinymce-spellchecker'),
    url(r'^filebrowser/$', filebrowser, name='tinymce-filebrowser'),
    url(r'^tinymce4.css', css, name='tinymce-css'),
    url(r'^spellcheck-callback.js', spell_check_callback, name='tinymce-spellcheck-callback')
]

main/urls.py
from django.conf.urls import url
from django.views.decorators.cache import never_cache
from main.views import MainPageView, getRandomSliderImages

urlpatterns = [
    url('slider_images', getRandomSliderImages, name="slider_images"),
    url(r'^$', never_cache(MainPageView.as_view()), name="main"),
]

medsmartcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from main.views import AdminkaPageView

urlpatterns = [
    url(r'^adminka/', AdminkaPageView.as_view(), name="adminka"),
    url(r'^admin/', admin.site.urls),
    url(r'^goods/', include('goods.urls')),
    url(r'^services/', include('services.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^contacts/', include('contacts.urls')),
    url(r'^companyinfo/', include('companyinfo.urls')),
    url(r'^visits/', include('visits.urls')),
    url(r'^login/', auth_views.LoginView.as_view(template_name = "login.html"), name = "login"),
    url(r'^logout/', auth_views.LogoutView.as_view(), name = "logout"),
    url('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

goods/models.py
from tinymce import HTMLField
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from visits.tasks import remove_redis_key

def validate_price(value):
    try:
        f = float(value)
    except:
        raise ValidationError('%(value)s is not an even number', params={'value' : value})

class Country(models.Model):
    class Meta:
        verbose_name = 'страна'
        verbose_name_plural = 'страны'
        ordering = ['name']
    name = models.CharField(max_length = 50, verbose_name = 'Название', unique = True)
    def __str__(self):
        return self.name

class Manufacturer(models.Model):
    class Meta:
        verbose_name = 'производитель'
        verbose_name_plural = 'производители'
        ordering = ['name']
    name = models.CharField(max_length = 50, verbose_name = 'Название', unique = True)
    country = models.ForeignKey(Country, on_delete = models.PROTECT, verbose_name = 'Страна происхождения', default = None)
    logo_image = models.ImageField(upload_to = 'manufacturers/images', verbose_name = 'Логотип', default = None, null = True, blank = True)
    def __str__(self):
        return self.name + ' (' +str(self.country) + ')'

class Category(models.Model):
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['level_index_field','name']
    name = models.CharField(max_length = 50, verbose_name = 'Название', unique = True)
    parent_category = models.ForeignKey('self', on_delete = models.PROTECT, verbose_name = 'Родительская категория', default = None, null = True, blank = True)
    image = models.ImageField(upload_to = 'categories/images', verbose_name = 'Изображение', default = None, null = True, blank = True)
    level_index_field = models.CharField(max_length = 500, verbose_name = 'Индекс вложенности', default = None, editable = False, null = True)
    def __str__(self):
        return '.  '*(self.level() - 1) + self.name
    def get_absolute_url(self):
        return reverse("goods", kwargs = {"pk": self.pk})
    def level(self):
        lvl = 1
        if self.parent_category:
            lvl += self.parent_category.level()
        return lvl
    def level_index(self):
        lvl_ind = str(self.pk)
        if self.parent_category:
            lvl_ind = self.parent_category.level_index() + lvl_ind
        else:
            lvl_ind = '_' + lvl_ind
        return lvl_ind
    def recalc_level_index(self):
        cats = Category.objects.filter(parent_category = self)
        if cats:
            for cat in cats:
                obj = Category.objects.get(pk = cat.pk)
                obj.save(force_update = True)
    def ancestors(self):
        ancs = list()
        if self.parent_category:
            ancs.append(self.parent_category)
            ancs = self.parent_category.ancestors() + ancs
        else:
            ancs.append(None)
        return ancs
    def childs(self):
        cats = Category.objects.all()
        childs = []
        for cat in cats:
            if cat.parent_category == self:
                childs.append(cat)
        return childs
    def build_child_tree(self):
        d = {}
        d[self.name] = []
        childs = self.childs()
        for kid in childs:
            d[self.name].append(kid.build_child_tree())
        return d    

    def save(self, *args, **kwargs):
        if None == self.level_index_field:
            self.level_index_field = self.level_index()
            super(Category, self).save(*args, **kwargs)
        else:
            obj = Category.objects.get(pk = self.pk)
            force_update = kwargs.get('force_update', False)
            if obj.parent_category != self.parent_category or force_update:
                if self.parent_category:
                    if self in self.parent_category.ancestors():
                        raise ValidationError('Циклическая ссылка в родительской категории!')
                self.level_index_field = self.level_index()
                super(Category, self).save(*args, **kwargs)
                self.recalc_level_index()
                return
        super(Category, self).save(*args, **kwargs)

class Good(models.Model):
    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['name']
    name = models.CharField(max_length = 50, verbose_name = 'Название')
    category = models.ForeignKey(Category, on_delete = models.PROTECT, verbose_name = 'Категория', default = None)
    content = HTMLField('Content')
    manufacturer = models.ForeignKey(Manufacturer, on_delete = models.PROTECT, verbose_name = 'Производитель', default = None)
    featured = models.BooleanField(default = False, db_index = True, verbose_name = 'Рекомендуемый товар')
    image = models.ImageField(upload_to = 'goods/images', verbose_name = 'Изображение', default = None, null = True)
    reg_number = models.CharField(max_length = 50, verbose_name = 'Регистрационное свидетельство', default = None, null = True)
    reg_exp_date = models.DateField(verbose_name = 'Дата окончания регистрации', default = None, null = True)
    def __str__(self):
        return self.name  + ' (' + str(self.category) + ')'
    def save(self, *args, **kwargs):
        try:
            this_record = Good.objects.get(pk = self.pk)
            if this_record.image != self.image:
                this_record.image.delete(save = False)
        except:
            pass
        super(Good, self).save(*args, **kwargs)
    def delete(self, *args, **kwargs):
        """Method of deleting model record.

        Before totaly removing model record we must delete image file
        associated with record and then asynchronously remove 
        visits key from redis cache.
        """
        self.image.delete(save = False)
        path = self.get_absolute_url()
        remove_redis_key.apply_async(args = [path],
        retry = True,
        retry_policy =
        {'max_retries': 20,
        'interval_start': 0.01,
        'interval_step': 0.3,
        'interval_max': 6,})
        super(Good, self).delete(*args, **kwargs)
    def get_absolute_url(self):
        return reverse("goods_detail", kwargs = {"pk": self.pk})

goods/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView, ContextMixin
from django.views.generic.edit import UpdateView
from generic.mixins import PageNumberMixin
from goods.models import Good, Category
from django import forms
from tinymce import TinyMCE
from generic.mixins import CompanyInfoMixin
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse

from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.core.cache import cache, caches
from django.core.serializers import serialize, deserialize
from django.conf import settings
from visits.generic.count_visitors import count_visitors

from rest_framework.generics import ListAPIView
from rest_framework.serializers import Serializer
from .serializers import CategorySerializer

class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = '__all__'
    content = forms.CharField(label = 'Описание', widget=TinyMCE())


class GoodsPageView(PageNumberMixin, ListView, CompanyInfoMixin):
    model = Good
    template_name = 'goods.html'
    paginated_by = 10
    cat = None
    @count_visitors
    def get(self, request, *args, **kwargs):
        if self.kwargs['pk'] == None:
            self.cat = None
        else:
            self.cat = Category.objects.get(pk = self.kwargs['pk'])
        return super(GoodsPageView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodsPageView, self).get_context_data(**kwargs)
        if self.cat:
            context['ancestors'] = self.cat.ancestors()
        else:
            context['ancestors'] = [None, ]
        #key = 'subgroups:' + (str(self.cat.id) if self.cat else 'parent')
        #if key in cache:
        #    context['subgroups'] =  deserialize('json', cache.get(key))
        #else:
        #    context['subgroups'] = Category.objects.filter(parent_category = self.cat)
        #    values = serialize('json', context['subgroups'])
        #    cache.set(key, values, timeout = 900)           
        context['subgroups'] = Category.objects.filter(parent_category = self.cat)
        context['category'] = self.cat
        context['goods'] = Good.objects.filter(category = self.cat)
        return context
    def get_queryset(self):
        goods = Good.objects.filter(category = self.cat)
        return goods

class GoodDetailPageView(PageNumberMixin, DetailView, CompanyInfoMixin):
    model = Good
    template_name = 'good.html'
    @count_visitors
    def get(self, request, *args, **kwargs):
        self.category = Good.objects.get(pk = self.kwargs['pk']).category
        return super(GoodDetailPageView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodDetailPageView, self).get_context_data(**kwargs)
        context['ancestors'] = self.category.ancestors()
        return context

class GoodCreateView(PageNumberMixin, TemplateView, CompanyInfoMixin):
    template_name = 'good_edit.html'
    cat = None
    form = None

    def get(self, request, *args, **kwargs):
        if self.kwargs['pk'] == None:
            self.category = None
        else:
            self.category = Category.objects.get(pk = self.kwargs['pk'])
        self.form = GoodForm(initial = {'category': self.category})
        return super(GoodCreateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodCreateView, self).get_context_data(**kwargs)
        context["form"] = self.form
        context['category'] = self.category
        context['ancestors'] = self.category.ancestors()
        context['form_caption'] = 'Добавить товар'
        context['header_caption'] = 'Добавить товар'
        context['submit_button_caption'] = 'Добавить'
        return context

    def post(self, request, *args, **kwargs):
        self.form = GoodForm(request.POST, request.FILES)
        if self.kwargs["pk"] == None:
            self.category = Category.objects.first()
        else:
            self.category = Category.objects.get(pk = self.kwargs["pk"])
        if self.form.is_valid():
            self.form.save()
            return redirect(reverse("goods", kwargs = {"pk": self.category.pk}))
        return super(GoodCreateView, self).get(request, *args, **kwargs)

class GoodUpdateView(PageNumberMixin, UpdateView, CompanyInfoMixin):
    model = Good
    template_name = 'good_edit.html'
    fields = '__all__'
    good = None
    form = None

    def get(self, request, *args, **kwargs):
        if self.kwargs['pk'] == None:
            self.good = None
        else:
            self.good = Good.objects.get(pk = self.kwargs['pk'])
        self.form = GoodForm(instance = self.good)
        return super(GoodUpdateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GoodUpdateView, self).get_context_data(**kwargs)
        context["form"] = self.form
        context['category'] = self.good.category
        context['ancestors'] = self.good.category.ancestors()
        context['form_caption'] = 'Редактировать товар'
        context['header_caption'] = 'Редактировать товар'
        context['submit_button_caption'] = 'Сохранить'
        return context

    def post(self, request, *args, **kwargs):
        if self.kwargs['pk'] == None:
            self.good = None
        else:
            self.good = Good.objects.get(pk = self.kwargs['pk'])
        self.form = GoodForm(request.POST, request.FILES, instance = self.good)
        if self.form.is_valid():
            self.form.save()
            return redirect(reverse("goods", kwargs = {"pk": self.good.category.pk}))
        return super(GoodUpdateView, self).get(request, *args, **kwargs)

class CategoryListView(ListAPIView):
    serializer_class = CategorySerializer
    def get_queryset(self):
        objs = Category.objects.all()
        for ob in objs:
            if ob.parent_category:
                ob.parent_name = ob.parent_category.name
            else:
                ob.parent_name = ''
        return objs

def category_menu(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            data = {}
            cats = Category.objects.filter(parent_category__isnull = True)
            for cat in cats:
                data[cat.name] = cat.build_child_tree()
            return JsonResponse(data)
        else:
            return HttpResponse(status = 401, content = '<h1>Unsufficient privileges for performing request!</h1>', charset = 'utf-8')
    else:
        return HttpResponseNotAllowed('<h1>Unsupported HTTP method!</h1>')

goods/templates/good.html
{% extends "base.html" %}
{% load staticfiles %}
{% load humanize %}
{% block styles %}
    <link href="{% static "css/goods_detail.css" %}" rel="stylesheet"/>
{% endblock %}
{% block title %}
    Информация о товаре
{% endblock %}
<p>
{% block breadcrumbs%}
    {{ block.super }}
    {% for anc in ancestors %}
        {% ifequal anc None %}
            <a class="breadcrumb" href="{% url "goods"%}"> / Каталог товаров </a>
        {% else %}
            <a class="breadcrumb" href="{% url "goods" pk=anc.pk%}">/ {{ anc.name }} </a>
        {% endifequal %}
    {% endfor %}
    <a class="breadcrumb"  href="{% url "goods" pk=object.category.pk%}"> / {{ object.category.name }}</a>
    <span class="breadcrumb"  href="{% url "goods_detail" pk=object.pk%}"> / {{ object.name }}</span>
{% endblock %}
</p>
{% block content %}
    <h1>{{ object.name }}</h1>
    {% if perms.goods.edit_good %}
        <section id="permissions_section">
            <p>
                <a href="{% url "goods_edit" pk=object.pk %}">
                    + Редактировать товар
                </a>
            </p>
        </section>
    {% endif %}
    <section id="specification_section">
        <div id="manufacturer" class="specification">
            <p class="spec_name">
                Производитель:&nbsp;
            </p>
            <p class="spec_value">
                {{ object.manufacturer }}
            </p>
        </div>
        <div id="reg_number" class="specification">
            <p class="spec_name">
                Регистрация:&nbsp;
            </p>
            <p class="spec_value">
                {% ifnotequal object.reg_number None %}
                    {{ object.reg_number }}
                {% else %}
                    отсутствует
                {% endifnotequal %}
            </p>
        </div>
        <div id="reg_exp_date" class="specification">
            <p class="spec_name">
                Дата окончания:&nbsp;
            </p>
            <p class="spec_value">
                {% ifnotequal object.reg_exp_date None %}
                    {{ object.reg_exp_date }}
                {% else %}
                    отсутствует
                {% endifnotequal %}
            </p>
        </div>
        <div class="specification">
            <img src = "{{ MEDIA_URL }}{{ object.image }}"/>
        </div>
    </section>
    <section id="content_section">
        <p>
            Описание:
        </p>
        <div id="content">
            <br/>
            {{ object.content|safe }}
        </div>
    </section>
    <p class="go_back_label">
        <a href="{% url "goods" pk=object.category.pk %}?page={{ pn }}">&lt;&nbsp;Назад</a>
    </p>
    <script>
        function clearOutStyles(elem){
            var tags = (!elem) ? document.getElementById('content').childNodes : elem.childNodes;
            for(var i = 0; i < tags.length; i++)
                if (tags[i].style)
                    tags[i].removeAttribute('style');
            for(var i = 0; i < tags.length; i++)
                if (tags[i] instanceof HTMLElement)
                    clearOutStyles(tags[i]);
        };
        clearOutStyles();
    </script>
{% endblock %}

goods/templates/good_add.html
{% extends "base.html" %}
{% block title %}
Добавить товар
{% endblock %}
{% block content %}
    <h2>Добавление товара в каталог</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% include "generic/form.html" %}
        <div class="submit-button"><input type="submit" value="Добавить"></div>
    </form>
    <p>
        <a href="{% url "goods" pk=category.pk %}?page={{ pn }}">Назад</a>
    </p>
{% endblock %}

goods/templates/good_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
    <link rel="stylesheet" href="{% static "css/good_edit.css" %}"/>
{% endblock %}
{% block title %}
    {{ form_caption }}
{% endblock %}
{% block media %}
    {{ form.media }}
{% endblock %}
<p>
{% block breadcrumbs %}
    {{ block.super }}&gt;
    {% for anc in ancestors %}
        {% ifequal anc None %}
            <a class="breadcrumb" href="{% url "goods"%}">Каталог товаров </a>
        {% else %}
            &gt;&nbsp;<a class="breadcrumb" href="{% url "goods" pk=anc.pk%}">{{ anc.name }}</a>
        {% endifequal %}
    {% endfor %}
    {% ifnotequal category None %}
        &gt;&nbsp;<a class="breadcrumb" href="{% url "goods" pk=category.pk%}">{{ category.name }}</a>
    {% endifnotequal %}
{% endblock %}
</p>
{% block content %}
    <h1>{{ header_caption }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% include "generic/form.html" %}
        <div class="submit-button">
            <input type="submit" value="{{ submit_button_caption }}">
        </div>
        <div class="submit-button">
            <input type="button" value="Отмена" src="{% url "goods" pk=category.pk%}">
        </div>
    </form>
    <p>
        <a href="{% url "goods" pk=category.pk %}?page={{ pn }}">&lt;Назад</a>
    </p>
{% endblock %}

goods/templates/goods.html
{% extends "base.html" %}
{% load staticfiles %}
{% block styles %}
<link href="{% static "css/goods.css" %}" rel="stylesheet"/>
{% endblock %}
{% block title %}
Каталог товаров
{% endblock %}
<p>
{% block breadcrumbs %}
    {{ block.super }}
        {% for anc in ancestors %}
            {% ifequal anc None %}
                {% ifnotequal category None %}
                    <a class="breadcrumb" href="{% url "goods"%}"> / Каталог товаров </a>
                {% else %}
                    <span class="breadcrumb" href="{% url "goods"%}"> / Каталог товаров </span>
                {% endifnotequal %}
            {% else %}
                <a class="breadcrumb" href="{% url "goods" pk=anc.pk%}">/ {{ anc.name }} </a>
            {% endifequal %}
        {% endfor %}
        {% ifnotequal category None %}
            <span class="breadcrumb" href="{% url "goods" pk=category.pk%}"> / {{ category.name }}</span>
        {% endifnotequal %}
{% endblock %}
</p>
{% block content %}
    <section id="subgroups_section">
        {% if subgroups %}
            {% for subgroup in subgroups %}
                <article class="subgroup_item">
                    <a href="{{ subgroup.get_absolute_url }}">
                        {% if subgroup.image %}
                            <img src="{{ MEDIA_URL }}{{ subgroup.image }}" class="item_img" alt=""/>
                        {% else %}
                            <img src="/media/categories/images/4f035e72-d85f-4e20-8906-ee5818209ce5_catalog.png" class="item_img" alt=""/>
                        {% endif %}
                    </a>
                    <a href="{{ subgroup.get_absolute_url }}" class="item_caption">
                        {{ subgroup.name }}
                    </a>
                </article>
            {% endfor %}
        {% endif %}
    </section>
    <section id="goods_section">
        {% if category %}
            {% if perms.goods.add_good %}
                <article id="good_permissions">
                    <p>
                        <a href="{% url "goods_add" pk=category.pk %}">
                            + Добавить товар
                        </a>
                    </p>
                </article>
            {% endif %}
            {% if goods %}
                {% for good in goods %}
                    <article class="good_item">
                        <a href="{{ good.get_absolute_url }}">
                            <img src="{{ MEDIA_URL }}{{ good.image }}" class="item_img" alt=""/>
                        </a>
                        <a href="{{ good.get_absolute_url }}" class="item_caption">
                            {{ good.name}}, {{  good.manufacturer }}
                        </a>
                    </article>
                {% endfor %}
            {% endif %}
        {% endif %}
    </section>
    <br/>
{% endblock %}
{% block scripts %}
    <script src="{% static "js/goods.js"%}"></script>
{% endblock %}

goods/templates/goods_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load humanize %}
{% block styles %}
    <link href="{% static "css/goods_detail.css" %}" rel="stylesheet"/>{% endblock %}
{% block title %}
    Информация о товаре
{% endblock %}
{% block content %}
    <h1>Информация о товаре</h1>
    <h2>{{ object.name }}</h2>
    <section id="header_section">
        <img src = "{{ MEDIA_URL }}{{ object.image }}"/>
        <p id="manufacturer">
            {{ object.manufacturer }}
        </p>
        <p id="price">
            {{ object.price|floatformat:2|intcomma }}
        </p>
    </section>
    <section id="content_section">
        <p id="content">
            <br/>
            {{ object.content }}
        </p>
    </section>
{% endblock %}